#!/usr/bin/env python3

import sqlite3
import os

DB_PATH = '/tmp/hrm_data.sqlite'

db = sqlite3.connect(DB_PATH)
cursor = db.cursor()
cursor.execute('SELECT hr FROM hrm ORDER BY id DESC LIMIT 1')
hr = cursor.fetchone()

print("HR=%s" % hr)

db.close()
